baseurl = "https://joshuamarquez.github.io/"
title = "joshuamarquez.github.io"
languageCode = "en-us"
copyright = "Joshua Marquez"
googleAnalytics = "UA-77414174-1"
pagerSize = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
theme = "coder"

[services]
[services.disqus]
Shortname = "joshuamarquez"

[params] # theme parameters
    author = "Joshua Marquez" # author's name
    info = "Full-stack developer" # author's job title or info
    description = "Joshua Marquez's personal website" # site description
    keywords = "blog,developer,personal,back-end,front-end,full-stack,devops,engineer" # site keywords

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/joshuamarquez"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://x.com/joshuaoutside"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/josuemarquezn/"
[[params.social]]
    name = "Instagram"
    weight = 4
    url = "https://www.instagram.com/josueoutside/"
[[params.social]]
    name = "Email"
    weight = 5
    url = "mailto:joshua.marquez.n@gmail.com"
[[params.social]]
    name = "Photos"
    weight = 6
    url = "https://joshuamarquezn.darkroom.com/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url = "/posts/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/page/about/"
